FROM bitriseio/docker-android

RUN apt-get update && apt-get install -y xvfb chromium-browser

ENV DISPLAY :99
ENV CHROME_BIN /usr/bin/chromium

COPY entrypoint.sh /
RUN chmod a+x /entrypoint.sh

WORKDIR /bitrise/src